language: ruby
rvm:
  - 1.8.7
  - 2.2.3
env:
  - PUPPET_VERSION=3.8.2
  - PUPPET_VERSION=4.2.2
matrix:
  exclude:
    - rvm: 2.2.3
      env: PUPPET_VERSION="~> 4.0.0"
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--color --format documentation'"
bundler_args: ''
notifications:
  email:
    - project@bendler-net.de
