language: ruby
cache: bundler
bundler_args:
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--color --format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION=3.8.3
  - rvm: 2.2.3
    env: PUPPET_GEM_VERSION=3.8.3 FUTURE_PARSER="yes"
  - rvm: 2.2.3
    env: PUPPET_GEM_VERSION=4.2.2 STRICT_VARIABLES="yes"
notifications:
  email:
    - project@bendler-net.de
